# Generated by Django 3.2.15 on 2022-08-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcctStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ordertype', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('units', models.FloatField()),
                ('realized_equity_change', models.DecimalField(decimal_places=2, max_digits=9)),
                ('realized_equity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
