# Generated by Django 3.2.15 on 2022-08-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=9)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pct_pnl', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
